TrajectoryPlannerROS:  
  max_vel_x: 0.3  
  min_vel_x: 0.1  
  max_vel_theta: 0.4  
  min_in_place_vel_theta: 0.4  
 
  acc_lim_theta: 2.0  
  acc_lim_x: 2.0  
  acc_lim_y: 2.0  
 
  holonomic_robot: true