map_type: costmap
origin_z: 0.0
z_resolution: 0.2
z_voxels: 2

obstacle_range: 2.5
raytrace_range: 3.0

publish_voxel_map: false
transform_tolerance: 0.5
meter_scoring: true

footprint: [[-0.21, -0.165], [-0.21, 0.165], [0.21, 0.165], [0.21, -0.165]]
footprint_padding: 0.1

#plugins:
#- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
#- {name: inflater_layer, type: "costmap_2d::InflationLayer"}

obstacles_layer:
  observation_sources: point_cloud_sensor
  point_cloud_sensor: {sensor_frame: /map, data_type: PointCloud2, topic: /pclPoint_out, marking: true, clearing: true, min_obstacle_height: 0.15, max_obstacle_height: 1.0}

inflater_layer:
  inflation_radius: 0.05