obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.30
inflation_radius: 0.55
observation_sources: point_cloud_sensor
point_cloud_sensor: {sensor_frame: /map, data_type: PointCloud, topic: /pclPoint_out, marking: true, clearing: true}