global_costmap:
   map_topic: /projected_map
   global_frame: /map
   robot_base_frame: /base_link
   update_frequency: 1.0
   publish_frequency: 0.5
   static_map: true
   transform_tolerance: 0.5
   resolution: 0.05
   inflation_radius: 0.1
   cost_scaling_factor: 2.0